name = "VegaGraphs"
uuid = "f0eb87fe-36d4-4e4c-b3c1-2826169d31b7"
authors = ["Anwesh Saha <anweshsaha21@iitk.ac.in> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
